name: Claude Code Review

on:
  pull_request:
    # Only run the first time the PR is opened or when it is marked as ready for review
    # This is to avoid claude from automatically reviewing the PR every time there's a new commit
    types: [opened, ready_for_review]

jobs:
  claude-review:
    # Run for non-draft PRs that are not marked to be skipped
    if: (github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name, 'option.do-not-merge') && github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            Be constructive and helpful in your feedback. Don't be overly polite or verbose, it is ok to be direct.
            Use `gh pr comment:*` for top-level comments.
            Only your GitHub comments that you post will be seen, so don't submit your review as a normal message, just as comments.
          # Add specific tools for running tests or linting
          claude_args: |
            --allowedTools "
              Bash(pnpm install),
              Bash(pnpm test:*),
              Bash(pnpm fmt:sol),
              Bash(pnpm snapshot:*),
              Bash(pnpm compile:*),
              Bash(pnpm layout:*),
              Bash(cat *),
              Bash(find *),
              Bash(grep *),
              Bash(ls *),
              Bash(gh pr comment:*), 
              Bash(gh pr diff:*), 
              Bash(gh pr view:*),
              WebFetch(domain:docs.anthropic.com)
            "
          use_sticky_comment: true
